stages:
  - build


build_master:
  stage: build
  image: docker:stable
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  script:
    - docker build --pull -t "$CI_REGISTRY_IMAGE" ./
    - docker push "$CI_REGISTRY_IMAGE"
  only:
    - master


# On branches except master: Only test build, don't push to registry
build:
  stage: build
  image: docker:stable
  script:
    - docker build --pull ./
  except:
    - master
